export {
  defaultDesktopAgentProvider,
  defaultDesktopBrowserUseConnectionMode,
  defaultDesktopDockIconStyle,
  defaultDesktopDockPlacement,
  defaultDesktopSleepPreventionMode,
  desktopAgentComposerDefaultsByProviderEqual,
  desktopAgentComposerDefaultsEqual,
  desktopAgentProviders,
  desktopBrowserUseConnectionModes,
  desktopDockIconStyles,
  desktopDockPlacements,
  desktopSleepPreventionModes,
  isDesktopAgentProvider,
  isDesktopBrowserUseConnectionMode,
  isDesktopDockIconStyle,
  isDesktopDockPlacement,
  isDesktopSleepPreventionMode,
  mergeDesktopAgentComposerDefaultsByProvider,
  normalizeDesktopAgentComposerDefaults,
  normalizeDesktopAgentComposerDefaultsByProvider,
  readInitialDockPlacementFromLocation,
  type DesktopAgentComposerDefaults,
  type DesktopAgentComposerDefaultsByProvider,
  type DesktopAgentProvider,
  type DesktopBrowserUseConnectionMode,
  type DesktopDockIconStyle,
  type DesktopDockPlacement,
  type DesktopSleepPreventionMode
} from "./core.ts";
